### PR TITLE
Initial IPv6 support

### PR DESCRIPTION
**Pull request by samip5**
**Description of the change**

IPv6 support

**Benefits**

Using with Mullvad is much better as it's also using it for both IPv6 and IPv4.

**Possible drawbacks**

Currently it defaults to dual-stack, which might be needed to do some checking to support single-stack thing like when running on a IPv6-only environment or IPv4-only.

**Applicable issues**

- fixes https://github.com/k8s-at-home/pod-gateway/issues/12

### CODE REVIEW

**Comment by angelnu** [comment]
So this works for people without dual-stack, could you please add 2 boolean settings such as IPV4_ENABLED and IPV6_ENABLED and then do the commands depending on them?

**Comment by dedene** [comment]
Thanks a lot for this! I also tested this, as I was just looking for a similar solution. The current implementation is depending on adding a net6.conf in https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gateway/templates/configmap.yaml.

Is it needed to have separate nat.conf and nat6.conf?

**Comment by samip5** [comment]
> Is it needed to have separate nat.conf and nat6.conf?

One might want to expose only on IPv6 or vice versa so yes.

**Comment by dedene** [comment]
I also needed to add a ping to the ipv6 gateway address to get it to reliably work immediatly: https://github.com/dedene/pod-gateway/commit/c2a9f591fdb16efc630b39b83a7f51766b5ff491#diff-d54596a8123109273f35d08877bd864894464deefc06410563ac9ff0f314432eR134

**Comment by samip5** [comment]
> I also needed to add a ping to the ipv6 gateway address to get it to reliably work immediatly: [dedene@c2a9f59#diff-d54596a8123109273f35d08877bd864894464deefc06410563ac9ff0f314432eR134](https://github.com/dedene/pod-gateway/commit/c2a9f591fdb16efc630b39b83a7f51766b5ff491#diff-d54596a8123109273f35d08877bd864894464deefc06410563ac9ff0f314432eR134)

Are you saying that a simple ping is needed for it to get DHCPv6 lease?

**Comment by samip5** [comment]
@dedene Could you maybe validate my code? It seems that the if statements are not quite working like I would want them to..

**Comment by dedene** [comment]
> @dedene Could you maybe validate my code? It seems that the if statements are not quite working like I would want them to..

@samip5 I tried to refactor it a bit to have less code deduplication (i.e. in the dhclient.conf setup) and keep closer to the original flow of code in setting up the iptables etc. You can have a look at https://github.com/dedene/pod-gateway/tree/feat/ipv6-support/bin

I also changed following:
- make the nat6.conf possible but optional (so there is no need to change the Helm chart in tandem with adding this change to the container)
- used IPV6 everywhere instead of IPv6 (it's just too easy to have typo's)
- I also changed the monitoring in the client sidecar. 

However it's not fully working yet, I'm always loosing the ipv6 connection over the VXLAN after several seconds. I'll continue looking into it later or if you see what's missing?

**Comment by dedene** [comment]
When looking at `ip -6 neighbour` on a client, the connection over the vxlan is continuously toggling between REACHABLE, STALE and FAILED.

**Comment by dedene** [comment]
Maybe we don’t need DHCPv6 and can use SLAAC with a static route?

**Comment by samip5** [comment]
> Maybe we don’t need DHCPv6 and can use SLAAC with a static route?

That should be quite simple actually, let's try that approach.

**Comment by samip5** [comment]
@dedene Using SLAAC will interfere with using IPv6 static addresses for port forwards though.

**Comment by dedene** [comment]
I think the static address needed for port forwarding can happily co-exists with SLAAC. With tcpdump I can see the router advertisements from dnsmasq are not going over the vxlan0 interface. 

When setting a much lower RA interval and lifetime it's easier to check: https://github.com/dedene/pod-gateway/blob/feat/ipv6-support/bin/gateway_sidecar.sh#L35 and using `tcpdump -vvvv -ttt -i vxlan0 icmp6 and ip6[40] == 134`

**Comment by samip5** [comment]
> I think the static address needed for port forwarding can happily co-exists with SLAAC. With tcpdump I can see the router advertisements from dnsmasq are not going over the vxlan0 interface. 
> 
> When setting a much lower RA interval and lifetime it's easier to check: https://github.com/dedene/pod-gateway/blob/feat/ipv6-support/bin/gateway_sidecar.sh#L35 and using `tcpdump -vvvv -ttt -i vxlan0 icmp6 and ip6[40] == 134`

BitTorrent would disagree with that assumption that they are fine to co-exist. In theory yes, but then the app needs to be configured to use the static for outgoing traffic and not the SLAAC one.

**Comment by angelnu** [comment]
I just released an update in the helm chart: https://github.com/angelnu/helm-charts/pull/62

**Comment by dedene** [comment]
> In theory yes, but then the app needs to be configured to use the static for outgoing traffic and not the SLAAC one.

Yeah you're right. 

I'm no IPv6 expert but as an experiment I've changed the gateway-admision-controller so it adds "Privileged" to the security context and we can set following before adding the vxlan interface:

```
sysctl -w net.ipv6.conf.default.accept_ra=2
sysctl -w net.ipv6.conf.all.accept_ra=2
sysctl -w net.ipv6.conf.default.autoconf=0
sysctl -w net.ipv6.conf.all.autoconf=0
```

Otherwise the vxlan interface will get a SLAAC address as soon as you add the interface and the tunnel is up. Next dhclient is properly assigning an ip but it fails to route trafffic (with tcpdump I see neighbour sollicitations but no responses).

**Comment by samip5** [comment]
Yeah, I'm at a loss at how this really should be done, I'm gonna try to replicate the issue on non k8s environment first to figure out how to use vxlan properly.

**Comment by samip5** [comment]
I think I found the issue with this: https://github.com/cilium/cilium/issues/26837

**Pull request closed without merging**
